#
# This is free software, lisence use MIT
#
# Copyright (C) 2019 P3TERX <https://p3terx.com>
# Copyright (C) 2019 KFERMercer <KFER.Mercer@gmail.com>
#
# <https://github.com/KFERMercer/OpenWrt-CI>
#

name: OpenWrt_open-vm-tools_6.12.x

on:
  push:
    branches:
      - master
  schedule:
      - cron:  '0 */3 * * *'
  release:
      types: [published]

jobs:

  build:

    runs-on: ubuntu-22.04

    steps:

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.25'
          check-latest: true

      - name: 查看机器配置
        run: |
         echo "警告⚠"
         echo "分配的服务器性能有限，若选择的插件过多，务必注意CPU性能！"
         echo -e "CPU性能排序: 7763 > 8370C > 8272CL > 8171M > E5-2673\n"
         echo "--------------------------CPU信息--------------------------"
         echo "CPU物理数量: $(cat /proc/cpuinfo | grep "physical id" | sort | uniq | wc -l)"
         echo "CPU核心数量: $(cat /proc/cpuinfo | grep "processor" | wc -l)"
         echo "CPU型号: $(cat /proc/cpuinfo | grep "model name" | head -n 1 | awk -F ': ' '{print $2}')"
         echo "--------------------------内存信息--------------------------"
         echo "已使用内存: $(free -m | grep Mem | awk '{print $3}') MB"
         echo "总内存: $(free -m | grep Mem | awk '{print $2}') MB"
         echo "--------------------------磁盘信息--------------------------"
         echo "磁盘状态: "
         df -h

      - name: Space cleanup
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
          sudo -E apt-get -qq update
          sudo -E apt-get -qq install $(curl -fsSL https://is.gd/depends_ubuntu_2204)
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Update & Install feeds
        run: |
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          # 修复报错：手动删除引发警告的冲突包，防止影响后续的 make defconfig
          rm -rf package/lean/ddns-scripts_dnspod

      - name: Generate configuration file
        run: |
          # 优化项：显式开启 Go 代理，确保你选的 netbird、frp 等插件能顺利下载
          export GO111MODULE=on
          export GOPROXY=https://goproxy.io,direct
          
          rm -f ./.config*
          touch ./.config
          #
          # ========================固件定制部分========================
          #
          #
          # 如果 不对本区块做出任何编辑, 则生成默认配置固件.
          #
          # 以下为定制化固件选项和说明:
          #
          #
          # 有些插件/选项是默认开启的, 如果想要关闭, 请参照以下示例进行编写:
          #
          #          =========================================
          #         |  # 取消编译VMware镜像:                   |
          #         |  cat >> .config <<EOF                   |
          #         |  # CONFIG_VMDK_IMAGES is not set        |
          #         |  EOF                                    |
          #          =========================================
          #
          #
          # 以下是一些提前准备好的一些插件选项.
          # 直接取消注释相应代码块即可应用. 不要取消注释代码块上的汉字说明.
          # 如果不需要代码块里的某一项配置, 只需要删除相应行.
          #
          # 如果需要其他插件, 请按照示例自行添加.
          # 注意, 只需添加依赖链顶端的包. 如果你需要插件 A, 同时 A 依赖 B, 即只需要添加 A.
          #
          # 无论你想要对固件进行怎样的定制, 都需要且只需要修改 EOF 回环内的内容.
          #
          # 编译x64固件:
          cat >> .config <<EOF
          CONFIG_TARGET_x86=y
          CONFIG_TARGET_x86_64=y
          CONFIG_TARGET_x86_64_Generic=y
          #CONFIG_HAS_TESTING_KERNEL=y
          CONFIG_TESTING_KERNEL=n
          #CONFIG_LINUX_6_6=y
          EOF
          # 镜像设置:
          # cat >> .config <<EOF
          # CONFIG_TARGET_ROOTFS_PARTSIZE=256
          # EOF
          # 固件压缩:
          # cat >> .config <<EOF
          # CONFIG_TARGET_IMAGES_GZIP=y
          # EOF
          # 编译UEFI固件:
          # cat >> .config <<EOF
          # CONFIG_EFI_IMAGES=y
          # EOF
          # IPv6支持:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_dnsmasq_full_dhcpv6=y
          # CONFIG_PACKAGE_ipv6helper=y
          # EOF
          # 多文件系统支持:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_kmod-fs-nfs=y
          # CONFIG_PACKAGE_kmod-fs-nfs-common=y
          # CONFIG_PACKAGE_kmod-fs-nfs-v3=y
          # CONFIG_PACKAGE_kmod-fs-nfs-v4=y
          # CONFIG_PACKAGE_kmod-fs-ntfs=n
          # CONFIG_PACKAGE_kmod-fs-squashfs=n
          # CONFIG_PACKAGE_kmod-fs-ntfs3-oot=y
          # EOF
          # USB3.0支持:
          # cat >> .config <<EOF
          # CONFIG_PACKAGE_kmod-usb-ohci=y
          # CONFIG_PACKAGE_kmod-usb-ohci-pci=y
          # CONFIG_PACKAGE_kmod-usb2=y
          # CONFIG_PACKAGE_kmod-usb2-pci=y
          # CONFIG_PACKAGE_kmod-usb3=y
          # EOF
          # 常用LuCI插件选择:
          cat >> .config <<EOF
          # CONFIG_PACKAGE_luci-app-adbyby-plus=y
          # CONFIG_PACKAGE_luci-app-aria2=y
          # CONFIG_PACKAGE_luci-app-baidupcs-web=y
          # CONFIG_PACKAGE_luci-app-docker=y
          # CONFIG_PACKAGE_luci-app-kodexplorer=y
          # CONFIG_PACKAGE_luci-app-minidlna=y
          # CONFIG_PACKAGE_luci-app-openvpn=y
          # CONFIG_PACKAGE_luci-app-openvpn-server=y
          # CONFIG_PACKAGE_luci-app-qbittorrent=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Kcptun=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Shadowsocks=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Server=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ShadowsocksR_Socks=y
          # CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_V2ray=y
          # CONFIG_PACKAGE_luci-app-ttyd=y
          # CONFIG_PACKAGE_luci-app-v2ray-server=y
          # CONFIG_PACKAGE_luci-app-verysync=y
          # CONFIG_PACKAGE_luci-app-webadmin=y
          # CONFIG_PACKAGE_luci-app-wireguard=y
          # CONFIG_PACKAGE_luci-app-wrtbwmon=y
          # CONFIG_PACKAGE_luci-app-koolproxyR=y
          # CONFIG_PACKAGE_luci-app-adguardhome=y
          # CONFIG_PACKAGE_luci-app-netdata=y
          # CONFIG_PACKAGE_luci-app-frpc=y
          #CONFIG_PACKAGE_luci-app-openclash=y
          # CONFIG_PACKAGE_luci-app-mihomo=y
          CONFIG_PACKAGE_luci-app-frps=y
          CONFIG_PACKAGE_luci-app-aliyundrive-webdav=n
          CONFIG_PACKAGE_luci-app-adbyby-plus=n
          CONFIG_PACKAGE_luci-app-unblockmusic=n
          CONFIG_PACKAGE_luci-app_transmission=n
          CONFIG_PACKAGE_luci-app-xlnetacc=n
          CONFIG_PACKAGE_luci-app-samba4=n
          CONFIG_PACKAGE_luci-app-ddns=n
          CONFIG_PACKAGE_luci-app-vsftpd=n
          CONFIG_PACKAGE_luci-app-accesscontrol=n
          CONFIG_PACKAGE_luci-app-ssr-plus=n
          CONFIG_PACKAGE_luci-app-vlmcsd=n
          CONFIG_PACKAGE_luci-app-openlist2=y
          CONFIG_PACKAGE_luci-app-lucky=y
          CONFIG_PACKAGE_luci-app-passwall=y
          ####CONFIG_PACKAGE_luci-app-passwall2=y
          CONFIG_PACKAGE_luci-app-wireguard=y
          CONFIG_PACKAGE_luci-proto-wireguard=y
          CONFIG_PACKAGE_luci-app-ttyd=y
          CONFIG_PACKAGE_luci-app-taskplan=y
          CONFIG_PACKAGE_luci-app-rtp2httpd=y
          #CONFIG_PACKAGE_luci-app-homeproxy=y
          EOF
          # LuCI主题:
          # #cat >> .config <<EOF
          # #CONFIG_PACKAGE_luci-theme-argon=y
          # #CONFIG_PACKAGE_luci-theme-netgear=y
          # #EOF
          # 常用软件包:
          cat >> .config <<EOF
          # CONFIG_PACKAGE_curl=y
          # CONFIG_PACKAGE_htop=y
          # CONFIG_PACKAGE_screen=y
          # CONFIG_PACKAGE_tree=y
          # CONFIG_PACKAGE_vim-fuller=y
          # CONFIG_PACKAGE_wget=y
          # CONFIG_PACKAGE_tvheadend=y
          # CONFIG_PACKAGE_ntfs3-oot=n
          # CONFIG_PACKAGE_mount=n
          # CONFIG_PACKAGE_server_box_monitor=y
          CONFIG_SING_BOX_WITH_ECH=y
          CONFIG_PACKAGE_nano=y
          CONFIG_PACKAGE_open-vm-tools=y
          CONFIG_PACKAGE_iperf3=y
          CONFIG_PACKAGE_iftop=y
          CONFIG_PACKAGE_tcpdump=y
          CONFIG_PACKAGE_pv=y
          CONFIG_PACKAGE_netbird=y
          #CONFIG_PACKAGE_wg-installer-server-hotplug-babeld=y
          #CONFIG_PACKAGE_wg-installer-client=y
          #CONFIG_PACKAGE_wg-installer-server=y
          ####CONFIG_PACKAGE_wg_wormhole=y
          EOF
          # 取消编译VMware镜像以及镜像填充 (不要删除被缩进的注释符号):
          cat >> .config <<EOF
          # CONFIG_TARGET_IMAGES_GZIP is not set
          # CONFIG_TARGET_IMAGES_KERNEL is not set
          # CONFIG_VMDK_IMAGES is not set
          # CONFIG_TARGET_ROOTFS_INITRAMFS is not set
          # # CONFIG_TARGET_ROOTFS_SQUASHFS is not set
          EOF
          #
          # ========================固件定制部分结束========================
          #
          sed -i 's/^[ \t]*//g' ./.config
          make defconfig

      - name: Make download
        run: |
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Compile the firmware
        id: compile
        continue-on-error: true
        run: |
          # 针对 4 核 CPU，初次编译改用 -j2 确保 boost 等重型包不溢出内存
          # 失败时自动切换单线程 V=s 输出报错详情
          make -j2 || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Check space usage
        if: (!cancelled())
        run: df -hT

      - name: Organize files
        id: organize
        if: steps.compile.outputs.status == 'success' && !cancelled()
        run: |
          mkdir -p ./artifact/buildinfo
          mkdir -p ./artifact/package
          cp -rf $(find ./bin/targets/ -type f -name "*.buildinfo" -o -name "*.manifest") ./artifact/buildinfo/
          cp -rf $(find ./bin/packages/ -type f -name "*.ipk") ./artifact/package/
          rm -rf ./bin/targets/*/*/*.buildinfo
          rm -rf ./bin/targets/*/*/*.manifest
          rm -rf ./bin/targets/*/*/sha256sums
          echo "status=success" >> $GITHUB_OUTPUT

      - name: Deliver buildinfo
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_buildinfo_6.12.x
          path: ./artifact/buildinfo/
          retention-days: 7
          compression-level: 9

      - name: Deliver package
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_package_6.12.x
          path: ./artifact/package/
          retention-days: 7
          compression-level: 9

      - name: Deliver firmware
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_firmware_6.12.x
          path: ./bin/targets/
          retention-days: 7
          compression-level: 9

      - name: Upload release asset
        if: github.event == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.YOURTOKEN }}
          file: ./artifact/firmware/*
          tag: ${{ github.ref }}
          file_glob: true
